version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: kolam-backend
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/generated_images:/app/generated_images
    networks:
      - kolam-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kolam-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - kolam-network

networks:
  kolam-network:
    driver: bridge

volumes:
  generated_images:
    driver: local
